/**
 * Dataset Export Service
 * Core logic for exporting annotated datasets in YOLO/COCO format
 */

const fs = require('fs').promises;
const path = require('path');
const archiver = require('archiver');
const crypto = require('crypto');
const Annotation = require('../models/Annotation');
const storage = require('./storage');
const {
  convertSubboxesToYOLO,
  formatYOLOSubboxText,
  validateYOLOCoordinates
} = require('./annotationService');
const {
  DEFAULT_SPLIT_RATIO,
  TEMP_DIR_PATH,
  EXPORT_FORMATS,
  YOLO_CLASS_NAMES,
  ANNOTATION_STATUS,
  BATCH_SIZE,
  ERROR_CODES,
  SPLIT_STRATEGY,
  MIN_FREE_DISK_SPACE
} = require('../constants/export');

/**
 * Ensure temp directory exists
 */
async function ensureTempDir() {
  try {
    await fs.mkdir(TEMP_DIR_PATH, { recursive: true });
  } catch (error) {
    throw new Error(`Failed to create temp directory: ${error.message}`);
  }
}

/**
 * Check available disk space
 * @returns {Promise<number>} - Available space in bytes
 */
async function checkDiskSpace() {
  try {
    const { exec } = require('child_process');
    const { promisify } = require('util');
    const execPromise = promisify(exec);
    
    const { stdout } = await execPromise(`df -k ${TEMP_DIR_PATH} | tail -1 | awk '{print $4}'`);
    const availableKB = parseInt(stdout.trim());
    return availableKB * 1024; // Convert to bytes
  } catch (error) {
    console.warn('Could not check disk space:', error.message);
    return MIN_FREE_DISK_SPACE; // Assume enough space
  }
}

/**
 * Split dataset by patient to avoid data leakage
 * @param {Array} images - Array of image records
 * @param {Object} splitRatio - { train, val, test }
 * @returns {Promise<Object>} - { train: [...imageIds], val: [...], test: [...] }
 */
async function splitDatasetByPatient(images, splitRatio = DEFAULT_SPLIT_RATIO) {
  // Validate split ratios
  const sum = splitRatio.train + splitRatio.val + splitRatio.test;
  if (Math.abs(sum - 1.0) > 0.001) {
    throw new Error(`${ERROR_CODES.INVALID_SPLIT_RATIO}: Ratios must sum to 1.0, got ${sum}`);
  }
  
  if (splitRatio.train < 0.05 || splitRatio.val < 0.05 || splitRatio.test < 0.05) {
    throw new Error(`${ERROR_CODES.INVALID_SPLIT_RATIO}: Each split must be at least 5%`);
  }
  
  // Group images by patient
  const imagesByPatient = {};
  images.forEach(img => {
    if (!imagesByPatient[img.patient_id]) {
      imagesByPatient[img.patient_id] = [];
    }
    imagesByPatient[img.patient_id].push(img.id);
  });
  
  // Get unique patient IDs and shuffle
  const patientIds = Object.keys(imagesByPatient);
  const shuffled = patientIds.sort(() => Math.random() - 0.5);
  
  // Split patients
  const trainCount = Math.floor(shuffled.length * splitRatio.train);
  const valCount = Math.floor(shuffled.length * splitRatio.val);
  
  const trainPatients = shuffled.slice(0, trainCount);
  const valPatients = shuffled.slice(trainCount, trainCount + valCount);
  const testPatients = shuffled.slice(trainCount + valCount);
  
  // Assign images to splits
  const splits = {
    train: trainPatients.flatMap(pid => imagesByPatient[pid]),
    val: valPatients.flatMap(pid => imagesByPatient[pid]),
    test: testPatients.flatMap(pid => imagesByPatient[pid])
  };
  
  return splits;
}

/**
 * Generate data.yaml for YOLO training
 * @param {Object} splits - { train, val, test }
 * @returns {string} - YAML content
 */
function generateDataYaml(splits) {
  return `# YOLO Dataset Configuration
# Generated by NhaKhoa System

train: ./images/train
val: ./images/val
test: ./images/test

nc: 2
names: ['no_plaque', 'has_plaque']

# Dataset statistics
# Train images: ${splits.train.length}
# Val images: ${splits.val.length}
# Test images: ${splits.test.length}
# Total: ${splits.train.length + splits.val.length + splits.test.length}
`;
}

/**
 * Generate classes.txt file
 * @returns {string} - Class names one per line
 */
function generateClassesTxt() {
  return YOLO_CLASS_NAMES.join('\n');
}

/**
 * Sanitize filename for safe file system operations
 * @param {string} filename - Original filename
 * @returns {string} - Sanitized filename
 */
function sanitizeFilename(filename) {
  return filename
    .replace(/[^a-zA-Z0-9._-]/g, '_')
    .replace(/_{2,}/g, '_')
    .toLowerCase();
}

/**
 * Extract object name from MinIO URL
 * @param {string} url - MinIO URL
 * @returns {string} - Object name
 */
function extractObjectName(url) {
  // URL format: /nhakhoa/visits/123/image.jpg
  // MinIO object format: visits/123/image.jpg (without bucket name)
  return url.replace(/^\/nhakhoa\//, '');
}

/**
 * Download image from MinIO
 * @param {string} url - MinIO URL
 * @param {string} destPath - Destination file path
 */
async function downloadImage(url, destPath) {
  try {
    const objectName = extractObjectName(url);
    const buffer = await storage.downloadFile(objectName);
    await fs.writeFile(destPath, buffer);
  } catch (error) {
    console.error(`Failed to download image ${url}:`, error.message);
    throw error;
  }
}

/**
 * Process images in batches to avoid memory overflow
 * @param {Array} items - Items to process
 * @param {Function} processFn - Async function to process each item
 * @param {number} batchSize - Batch size
 */
async function processBatch(items, processFn, batchSize = BATCH_SIZE) {
  const results = [];
  for (let i = 0; i < items.length; i += batchSize) {
    const batch = items.slice(i, i + batchSize);
    const batchResults = await Promise.all(batch.map(processFn));
    results.push(...batchResults);
  }
  return results;
}

/**
 * Generate YOLO dataset
 * @param {Object} params - { visitIds, patientIds, splitRatio, filters, format }
 * @returns {Promise<Object>} - { exportId, zipPath, stats }
 */
async function generateYOLODataset(params) {
  const {
    visitIds,
    patientIds = null,
    splitRatio = DEFAULT_SPLIT_RATIO,
    filters = {},
    format = EXPORT_FORMATS.YOLO
  } = params;
  
  // Check disk space
  const availableSpace = await checkDiskSpace();
  if (availableSpace < MIN_FREE_DISK_SPACE) {
    throw new Error(`${ERROR_CODES.INSUFFICIENT_SPACE}: Only ${(availableSpace / 1024 / 1024 / 1024).toFixed(2)}GB available`);
  }
  
  // Create export directory
  await ensureTempDir();
  const exportId = `exp_${crypto.randomUUID()}`;
  const exportDir = path.join(TEMP_DIR_PATH, exportId);
  await fs.mkdir(exportDir, { recursive: true });
  
  try {
    // 1. Fetch exportable images
    console.log(`Fetching annotated images for visits: ${visitIds.join(', ')}`);
    const images = await Annotation.getFullyAnnotatedImages(visitIds, filters);
    
    if (images.length === 0) {
      throw new Error(`${ERROR_CODES.NO_ANNOTATED_IMAGES}: No fully annotated images found`);
    }
    
    console.log(`Found ${images.length} exportable images`);
    
    // 2. Split dataset by patient
    console.log('Splitting dataset by patient...');
    const splits = await splitDatasetByPatient(images, splitRatio);
    
    // 3. Fetch all subboxes for export
    const imageIds = images.map(img => img.id);
    console.log(`Fetching subboxes for ${imageIds.length} images...`);
    const allSubboxes = await Annotation.getSubboxesForExport(imageIds);
    
    // Group subboxes by image_id
    const subboxesByImage = {};
    allSubboxes.forEach(subbox => {
      if (!subboxesByImage[subbox.image_id]) {
        subboxesByImage[subbox.image_id] = [];
      }
      subboxesByImage[subbox.image_id].push(subbox);
    });
    
    // 4. Create directory structure
    const splitNames = ['train', 'val', 'test'];
    for (const split of splitNames) {
      await fs.mkdir(path.join(exportDir, 'images', split), { recursive: true });
      await fs.mkdir(path.join(exportDir, 'labels', split), { recursive: true });
    }
    
    // 5. Process images and generate YOLO labels
    let processedCount = 0;
    let skippedCount = 0;
    const stats = {
      totalImages: 0,
      totalSubboxes: 0,
      plaquePositive: 0,
      plaqueNegative: 0,
      splits: { train: 0, val: 0, test: 0 }
    };
    
    for (const [splitName, imageIdsInSplit] of Object.entries(splits)) {
      console.log(`Processing ${splitName} split: ${imageIdsInSplit.length} images`);
      
      for (const imageId of imageIdsInSplit) {
        try {
          const image = images.find(img => img.id === imageId);
          if (!image) {
            console.warn(`Image ${imageId} not found in images array`);
            continue;
          }
          
          const subboxes = subboxesByImage[imageId] || [];
          if (subboxes.length === 0) {
            console.warn(`Image ${imageId} has no subboxes, skipping`);
            skippedCount++;
            continue;
          }
          
          console.log(`Processing image ${imageId}: ${image.original_filename}, subboxes: ${subboxes.length}`);
          
          // Sanitize filename
          const sanitizedName = sanitizeFilename(image.original_filename);
          const baseName = path.parse(sanitizedName).name;
          const imageExt = path.parse(image.original_filename).ext || '.jpg';
          
          // Download image
          const imageDest = path.join(exportDir, 'images', splitName, `${baseName}${imageExt}`);
          console.log(`Downloading from ${image.url} to ${imageDest}`);
          await downloadImage(image.url, imageDest);
          
          // Convert subboxes to YOLO format
          const yoloSubboxes = convertSubboxesToYOLO(subboxes, image.width, image.height);
          
          // Validate coordinates
          const validSubboxes = yoloSubboxes.filter(yolo => {
            const valid = validateYOLOCoordinates(yolo);
            if (!valid) {
              console.warn(`Invalid YOLO coordinates for image ${image.id}, skipping subbox`);
            }
            return valid;
          });
          
          if (validSubboxes.length === 0) {
            skippedCount++;
            continue;
          }
          
          // Write YOLO label file
          const labelContent = formatYOLOSubboxText(validSubboxes);
          const labelDest = path.join(exportDir, 'labels', splitName, `${baseName}.txt`);
          await fs.writeFile(labelDest, labelContent);
          
          // Update stats
          processedCount++;
          stats.totalImages++;
          stats.totalSubboxes += validSubboxes.length;
          stats.plaquePositive += validSubboxes.filter(s => s.class_id === 1).length;
          stats.plaqueNegative += validSubboxes.filter(s => s.class_id === 0).length;
          stats.splits[splitName]++;
          
        } catch (error) {
          console.error(`Failed to process image ${imageId}:`, error.message);
          skippedCount++;
        }
      }
    }
    
    console.log(`Processed: ${processedCount}, Skipped: ${skippedCount}`);
    
    if (processedCount === 0) {
      throw new Error(`${ERROR_CODES.NO_ANNOTATED_IMAGES}: No valid images could be processed`);
    }
    
    // 6. Generate data.yaml and classes.txt
    const dataYaml = generateDataYaml(stats.splits);
    await fs.writeFile(path.join(exportDir, 'data.yaml'), dataYaml);
    await fs.writeFile(path.join(exportDir, 'classes.txt'), generateClassesTxt());
    
    // 7. Generate README
    const readme = `# NhaKhoa Plaque Detection Dataset

## Dataset Information
- **Export ID**: ${exportId}
- **Generated**: ${new Date().toISOString()}
- **Format**: YOLO v5/v8/v11 compatible
- **Classes**: 2 (no_plaque, has_plaque)

## Statistics
- **Total Images**: ${stats.totalImages}
- **Total Subboxes**: ${stats.totalSubboxes}
- **Plaque Positive**: ${stats.plaquePositive}
- **Plaque Negative**: ${stats.plaqueNegative}

## Split Distribution
- **Train**: ${stats.splits.train} images
- **Val**: ${stats.splits.val} images
- **Test**: ${stats.splits.test} images

## Directory Structure
\`\`\`
dataset/
├── images/
│   ├── train/
│   ├── val/
│   └── test/
├── labels/
│   ├── train/
│   ├── val/
│   └── test/
├── data.yaml
└── classes.txt
\`\`\`

## YOLO Label Format
Each label file contains annotations in 6-field format:
\`<class> <x_center> <y_center> <width> <height> <parent_tooth_class>\`

Where:
- \`class\`: 0 (no_plaque) or 1 (has_plaque)
- \`x_center, y_center, width, height\`: Normalized [0-1] coordinates
- \`parent_tooth_class\`: YOLO class ID of parent tooth (0-15)

## Training with YOLOv8
\`\`\`python
from ultralytics import YOLO

# Load model
model = YOLO('yolov8n.pt')

# Train
model.train(data='data.yaml', epochs=100, imgsz=640)
\`\`\`

## Notes
- Dataset split by patient to prevent data leakage
- All coordinates validated and clamped to [0, 1]
- Only fully annotated images included
`;
    await fs.writeFile(path.join(exportDir, 'README.md'), readme);
    
    // 8. Create ZIP archive
    console.log('Creating ZIP archive...');
    const zipPath = path.join(TEMP_DIR_PATH, `${exportId}.zip`);
    await createZipArchive(exportDir, zipPath);
    
    // 9. Cleanup export directory
    await fs.rm(exportDir, { recursive: true, force: true });
    
    return {
      exportId,
      zipPath,
      stats
    };
    
  } catch (error) {
    // Cleanup on error
    try {
      await fs.rm(exportDir, { recursive: true, force: true });
    } catch (cleanupError) {
      console.error('Failed to cleanup after error:', cleanupError.message);
    }
    throw error;
  }
}

/**
 * Create ZIP archive from directory
 * @param {string} sourceDir - Source directory
 * @param {string} zipPath - Destination ZIP path
 */
async function createZipArchive(sourceDir, zipPath) {
  return new Promise((resolve, reject) => {
    const output = require('fs').createWriteStream(zipPath);
    const archive = archiver('zip', {
      zlib: { level: 6 } // Compression level
    });
    
    output.on('close', () => {
      console.log(`ZIP created: ${archive.pointer()} bytes`);
      resolve();
    });
    
    archive.on('error', (err) => {
      reject(err);
    });
    
    archive.pipe(output);
    archive.directory(sourceDir, false);
    archive.finalize();
  });
}

/**
 * Cleanup expired exports
 * @param {number} maxAgeSeconds - Maximum age in seconds
 */
async function cleanupExpiredExports(maxAgeSeconds = 3600) {
  try {
    const files = await fs.readdir(TEMP_DIR_PATH);
    const now = Date.now();
    
    for (const file of files) {
      const filePath = path.join(TEMP_DIR_PATH, file);
      const stat = await fs.stat(filePath);
      const ageSeconds = (now - stat.mtimeMs) / 1000;
      
      if (ageSeconds > maxAgeSeconds) {
        await fs.rm(filePath, { recursive: true, force: true });
        console.log(`Cleaned up expired export: ${file}`);
      }
    }
  } catch (error) {
    console.error('Cleanup error:', error.message);
  }
}

module.exports = {
  generateYOLODataset,
  splitDatasetByPatient,
  cleanupExpiredExports,
  ensureTempDir,
  checkDiskSpace
};
